# Generated by Django 3.0.5 on 2024-12-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_subject'),
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, to='quiz.Subject'),
        ),
    ]
