# Generated by Django 3.0.5 on 2024-12-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_subject'),
        ('teacher', '0003_auto_20241227_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='other_teachers', to='quiz.Class'),
        ),
    ]
