# Generated by Django 3.0.5 on 2024-12-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.AddField(
            model_name='marks',
            name='subject_marks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
