# Generated by Django 3.0.5 on 2024-12-29 08:01

from django.db import migrations


def populate_classes_and_subjects(apps, schema_editor):
    Class = apps.get_model('quiz', 'Class')
    Subject = apps.get_model('quiz', 'Subject')

    # Define static data
    static_data = [
        {
            "class_name": "Primary 1",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "LITERACY 1", "RELIGIOUS EDUCATION",
                "READING", "LUGANDA", "WRITING (LIT ll)"
            ],
        },
         {
            "class_name": "Primary 2",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "LITERACY 1", "RELIGIOUS EDUCATION",
                "READING", "LUGANDA", "WRITING (LIT ll)"
            ],
        },
         {
            "class_name": "Primary 3",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "LITERACY 1", "RELIGIOUS EDUCATION",
                "READING", "LUGANDA", "WRITING (LIT ll)"
            ],
        },
        {
            "class_name": "Primary 4",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "SCIENCE", "SOCIAL STUDIES"
            ],
        },
         {
            "class_name": "Primary 5",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "SCIENCE", "SOCIAL STUDIES"
            ],
        },
         {
            "class_name": "Primary 6",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "SCIENCE", "SOCIAL STUDIES"
            ],
        },
         {
            "class_name": "Primary 7",
            "subjects": [
                "MATHEMATICS", "ENGLISH", "SCIENCE", "SOCIAL STUDIES"
            ],
        },
    ]

    for entry in static_data:
        class_instance = Class.objects.create(class_name=entry["class_name"])
        for subject_name in entry["subjects"]:
            Subject.objects.create(class_name=class_instance, subject_name=subject_name)


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0007_subject'),  
    ]

    operations = [
        migrations.RunPython(populate_classes_and_subjects),
    ]
