# Generated by Django 5.1.4 on 2025-01-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='last_payment_date',
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='student.studentfee')),
            ],
        ),
    ]
