# Generated by Django 5.1.5 on 2025-01-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_configuration'),
        ('student', '0008_academicyear_term_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.academicyear'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.term'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'academic_year', 'term', 'assigned_class')},
        ),
    ]
